<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.taskflow.jsv</groupId>
    <artifactId>json-schema-validator-parent</artifactId>
    <version>${revision}</version>
    <modules>
        <module>json-schema-validator</module>
        <module>json-schema-validator-spring</module>
    </modules>
    <packaging>pom</packaging>
    <properties>
        <revision>0.3.0</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <log4j.version>2.0.1</log4j.version>
        <main.user.dir>${user.dir}</main.user.dir>
        <!--suppress UnresolvedMavenProperty -->
        <gpg.passphrase>${env.GPG_PASSPHRASE}</gpg.passphrase>
        <!--suppress UnresolvedMavenProperty -->
        <gpg.keyname>${env.GPG_KEYNAME}</gpg.keyname>
        <gpg.homedir>/Users/kevin/.gnupg</gpg.homedir>
    </properties>
    <description>Automated validation against JSON DSL data structures, supports arbitrary JSON data structures, and supports code generation</description>
    <url>https://github.com/kevinLuan/json-schema-validator</url>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <issueManagement>
        <system>Github Issues</system>
        <url>https://github.com/kevinLuan/json-schema-validator/issues</url>
    </issueManagement>
    <!-- Developer account -->
    <developers>
        <developer>
            <name>kevin.luan</name>
            <email>kevin_luan@126.com</email>
            <organization>taskflow technologies inc.</organization>
            <organizationUrl>https://github.com/kevinLuan/json-schema-validator</organizationUrl>
        </developer>
    </developers>
    <scm>
        <url>https://github.com/kevinLuan/json-schema-validator</url>
        <connection>scm:git:https://github.com/kevinLuan/json-schema-validator.git</connection>
        <developerConnection>scm:git:https://github.com/kevinLuan/json-schema-validator.git</developerConnection>
        <tag>HEAD</tag>
    </scm>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>[2.9.10.1,)</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>[2.9.10.1,)</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.persistence</groupId>
            <artifactId>persistence-api</artifactId>
            <version>1.0.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.25</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
            <scope>provided</scope>
        </dependency>
        <!-- google json pojo-->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.9</version>
        </dependency>
        <!-- mock 数据生成 -->
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <!--
            When publishing to a private repository, the plugin can replace ${revision} with the actual version number during the build process.
             -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.3.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
